### ISSUE TITLE
Terrible results on Red Blood Cells 

### ISSUE THREAD

**Issue by ashah03** [experiencor/basic-yolo-keras#100]
Hi,
After running your ipython notebook for the Red Blood Cells more or less as is for 8 epochs, I'm getting terrible results; the loss is ~0.7 and the boxes drawn on the image are completely arbitrary. When running the program, the training loss for every epoch is quite low (about 0.04) until the last mini-batch; then it shoots up to 0.7, and the val_loss is even higher. I'm not sure why this is, as I ran the code exactly as is (in a python file). Here is the code (in txt because I can't attach .py here):
[rbc.txt](https://github.com/experiencor/basic-yolo-keras/files/1577496/rbc.txt)

Here's an example of a picture:
<img width="559" alt="rbc_test" src="https://user-images.githubusercontent.com/25287297/34235354-0004d1dc-e5a6-11e7-9b0c-958f23f45dea.png">

**Comment by ashah03** [comment]
Here are the logs from the end of epoch 9
```
2017-12-21 01:07:26.386141: I tensorflow/core/kernels/logging_ops.cc:79] Loss Conf      [0.0121235428]
2017-12-21 01:07:26.386171: I tensorflow/core/kernels/logging_ops.cc:79] Loss Class     [0]
2017-12-21 01:07:26.386192: I tensorflow/core/kernels/logging_ops.cc:79] Total Loss     [0.653513551]
2017-12-21 01:07:26.386208: I tensorflow/core/kernels/logging_ops.cc:79] Current Recall         [0]
2017-12-21 01:07:26.386226: I tensorflow/core/kernels/logging_ops.cc:79] Average Recall         [0.761235833]
2017-12-21 01:07:55.867148: I tensorflow/core/kernels/logging_ops.cc:79] Dummy Line     [0]
2017-12-21 01:07:55.867289: I tensorflow/core/kernels/logging_ops.cc:79] Loss XY        [0.0813109428]
2017-12-21 01:07:55.867312: I tensorflow/core/kernels/logging_ops.cc:79] Loss WH        [0.494629592]
2017-12-21 01:07:55.867331: I tensorflow/core/kernels/logging_ops.cc:79] Loss Conf      [0.0130899614]
2017-12-21 01:07:55.867361: I tensorflow/core/kernels/logging_ops.cc:79] Loss Class     [0]
2017-12-21 01:07:55.867390: I tensorflow/core/kernels/logging_ops.cc:79] Total Loss     [0.589030504]
2017-12-21 01:07:55.867408: I tensorflow/core/kernels/logging_ops.cc:79] Current Recall         [0]
2017-12-21 01:07:55.867445: I tensorflow/core/kernels/logging_ops.cc:79] Average Recall         [0.757504284]
2017-12-21 01:08:24.892685: I tensorflow/core/kernels/logging_ops.cc:79] Dummy Line     [0]
2017-12-21 01:08:24.893270: I tensorflow/core/kernels/logging_ops.cc:79] Loss XY        [0.0913093388]
2017-12-21 01:08:24.893395: I tensorflow/core/kernels/logging_ops.cc:79] Loss WH        [0.472521663]
2017-12-21 01:08:24.893421: I tensorflow/core/kernels/logging_ops.cc:79] Loss Conf      [0.0127028851]
2017-12-21 01:08:24.893743: I tensorflow/core/kernels/logging_ops.cc:79] Loss Class     [0]
2017-12-21 01:08:24.893771: I tensorflow/core/kernels/logging_ops.cc:79] Total Loss     [0.576533854]
2017-12-21 01:08:24.893789: I tensorflow/core/kernels/logging_ops.cc:79] Current Recall         [0]
2017-12-21 01:08:24.893805: I tensorflow/core/kernels/logging_ops.cc:79] Average Recall         [0.753809094]
2017-12-21 01:08:53.620418: I tensorflow/core/kernels/logging_ops.cc:79] Dummy Line     [0]
2017-12-21 01:08:53.620484: I tensorflow/core/kernels/logging_ops.cc:79] Loss XY        [0.090484865]
2017-12-21 01:08:53.620506: I tensorflow/core/kernels/logging_ops.cc:79] Loss WH        [0.442576706]
2017-12-21 01:08:53.620527: I tensorflow/core/kernels/logging_ops.cc:79] Loss Conf      [0.01210202]
2017-12-21 01:08:53.620544: I tensorflow/core/kernels/logging_ops.cc:79] Loss Class     [0]
2017-12-21 01:08:53.620583: I tensorflow/core/kernels/logging_ops.cc:79] Total Loss     [0.545163572]
2017-12-21 01:08:53.620608: I tensorflow/core/kernels/logging_ops.cc:79] Current Recall         [0]
2017-12-21 01:08:53.620630: I tensorflow/core/kernels/logging_ops.cc:79] Average Recall         [0.750149846]
2017-12-21 01:09:22.113044: I tensorflow/core/kernels/logging_ops.cc:79] Dummy Line     [0]
2017-12-21 01:09:22.113958: I tensorflow/core/kernels/logging_ops.cc:79] Loss XY        [0.0866133943]
2017-12-21 01:09:22.114210: I tensorflow/core/kernels/logging_ops.cc:79] Loss WH        [0.42906642]
2017-12-21 01:09:22.114494: I tensorflow/core/kernels/logging_ops.cc:79] Loss Conf      [0.0129084587]
2017-12-21 01:09:22.114604: I tensorflow/core/kernels/logging_ops.cc:79] Loss Class     [0]
2017-12-21 01:09:22.114738: I tensorflow/core/kernels/logging_ops.cc:79] Total Loss     [0.528588295]
2017-12-21 01:09:22.114760: I tensorflow/core/kernels/logging_ops.cc:79] Current Recall         [0]
2017-12-21 01:09:22.114777: I tensorflow/core/kernels/logging_ops.cc:79] Average Recall         [0.746525943]
Epoch 00009: val_loss improved from 0.61616 to 0.57857, saving model to weights_rbc.h5
18/18 [==============================] - 1504s 84s/step - loss: 0.0344 - val_loss: 0.5786
Epoch 10/100
```

**Comment by experiencor** [comment]
@ashah03 Have you warmed up the network before the actual training? You may want to look at ```3. Start the training process``` in the readme for more information.

When using the python code, did you get pass epoch 10? You only provide the log until epoch 9.

**Comment by ashah03** [comment]
1. Do I need to follow those steps even when using the jupyter notebook you provided?
2. Yes, it got to epoch 18, but the loss was still very high.

**Comment by ashah03** [comment]
I tried using train.py, but I received this error:

```
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to
==================================================================================================
input_1 (InputLayer)            (None, 416, 416, 3)  0
__________________________________________________________________________________________________
model_1 (Model)                 (None, 13, 13, 1024) 50547936    input_1[0][0]
__________________________________________________________________________________________________
conv_23 (Conv2D)                (None, 13, 13, 30)   30750       model_1[1][0]
__________________________________________________________________________________________________
reshape_1 (Reshape)             (None, 13, 13, 5, 6) 0           conv_23[0][0]
__________________________________________________________________________________________________
input_2 (InputLayer)            (None, 1, 1, 1, 10,  0
__________________________________________________________________________________________________
lambda_2 (Lambda)               (None, 13, 13, 5, 6) 0           reshape_1[0][0]
                                                                 input_2[0][0]
==================================================================================================
Total params: 50,578,686
Trainable params: 50,558,014
Non-trainable params: 20,672
__________________________________________________________________________________________________
Loading pre-trained weights in full_yolo_backend.h5
Traceback (most recent call last):
  File "train.py", line 140, in <module>
    _main_(args)
  File "train.py", line 117, in _main_
    yolo.load_weights(config['train']['pretrained_weights'])
  File "/home/adit/notebooks/Yolo Experimentation/basic-yolo-keras/frontend.py", line 239, in load_weights
    self.model.load_weights(weight_path)
  File "/anaconda/envs/py35/lib/python3.5/site-packages/keras/engine/topology.py", line 2622, in load_weights
    load_weights_from_hdf5_group(f, self.layers)
  File "/anaconda/envs/py35/lib/python3.5/site-packages/keras/engine/topology.py", line 3115, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 44 layers into a model with 2 layers.
```

**Comment by experiencor** [comment]
Yes! You have to warm up the network before the actual training in both cases. 

I think that you are loading the wrong weight. Please read the readme, section ```2. Edit the configuration file```.

**Comment by sanelec1989** [comment]
Similar issue ..... Although the total loss reduces over epoch I observed that the "Loss Class" is always zero. On debugging I observed that the " true_box_class = tf.argmax(y_true[..., 5:], -1)" in loss function always return zero values. Following are the dumps of  "y_true[..., 5:]" and corresponding "true_box_class " :
[[[[[0][0][0][0][0]][[0][0][0][0][0]]**[[0][1][0][0][0]]**[[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]]][[[0][1][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]]][[[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]]][[[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][1][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][1][0][0]][[0][0][0][0][0]][[0][0][0][0][0]]][[[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][1][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]]][[[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]]][[[0][1][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][1][0][0]][[0][0][0][0][0]][[0][0][0][0][0]]][[[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]]][[[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][1][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][1][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]]][[[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]]][[[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]]][[[0][1][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][1][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]]][[[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]]]][[[[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]]][[[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]]][[[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]][[0][0][0][0][0]]]]...]

[[[[0 0 0 0 0][0 0 0 0 0]**[0 0 0 0 0]**[0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0]][[0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0]][[0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0]][[0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0]][[0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0]][[0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0]][[0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0]][[0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0]][[0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0]][[0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0]][[0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0]][[0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0]][[0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0]]][[[0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0]][[0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0]][[0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0][0 0 0 0 0]]]...]

Am i missing something ?
