### ISSUE TITLE
Issue running train.py

### ISSUE THREAD

**Issue by chingjunehao** [experiencor/basic-yolo-keras#121]
I get the problem like when tried to run train.py:
```
 Resource exhausted: OOM when allocating tensor with shape[16,16,208,208]
Traceback (most recent call last):
  File "C:\Users\User\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\client\session.py", line 1323, in _do_call
    return fn(*args)
  File "C:\Users\User\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\client\session.py", line 1302, in _run_fn
    status, run_metadata)
  File "C:\Users\User\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[16,16,208,208]
         [[Node: model_1/conv_2/convolution = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](model_1/max_pooling2d_1/MaxPool, conv_2/kernel/read)]]
         [[Node: loss/lambda_1_loss/truediv_7/_693 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1700_loss/lambda_1_loss/truediv_7", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 143, in <module>
    _main_(args)
  File "train.py", line 139, in _main_
    debug              = config['train']['debug'])
  File "C:\Users\User\Desktop\basic-yolo-keras-master\frontend.py", line 446, in train
    max_queue_size   = 8)
  File "C:\Users\User\Anaconda3\envs\py35\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\User\Anaconda3\envs\py35\lib\site-packages\keras\engine\training.py", line 2147, in fit_generator
    class_weight=class_weight)
  File "C:\Users\User\Anaconda3\envs\py35\lib\site-packages\keras\engine\training.py", line 1839, in train_on_batch
    outputs = self.train_function(ins)
  File "C:\Users\User\Anaconda3\envs\py35\lib\site-packages\keras\backend\tensorflow_backend.py", line 2357, in __call__
    **self.session_kwargs)
  File "C:\Users\User\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\client\session.py", line 889, in run
    run_metadata_ptr)
  File "C:\Users\User\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\client\session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\User\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\client\session.py", line 1317, in _do_run
    options, run_metadata)
  File "C:\Users\User\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\client\session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[16,16,208,208]
         [[Node: model_1/conv_2/convolution = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](model_1/max_pooling2d_1/MaxPool, conv_2/kernel/read)]]
         [[Node: loss/lambda_1_loss/truediv_7/_693 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1700_loss/lambda_1_loss/truediv_7", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```

When I run with Python3.5, (together with tensorflow and CUDA), the prompt displayed until 
```
Loading pre-trained weights in full_yolo_raccoon.h5
Epoch 1/3
```
Then start getting error, even the same when I tried with tiny yolo architecture.

**Comment by NPetsky** [comment]
I also ran into OutOfMemory, for me reducing the batch size helped.
I now train on 6GB GPU with Batchsize=8

**Comment by chingjunehao** [comment]
The error still occurs with batch size = 8/4, guess my gpu memory is not enough.

**Comment by NPetsky** [comment]
You could also try to reduce the image size maybe that helps?

**Comment by chingjunehao** [comment]
I have switch to a bigger gpu, but getting this error:
TypeError: Expected binary or unicode string, got Elemwise{add,no_inplace}.0

**Comment by experiencor** [comment]
Are you using python 3.5? Please also provide the full error.

**Comment by chingjunehao** [comment]
I'm using Python 2.7.14, the full error is:
```
Traceback (most recent call last):
  File "train.py", line 137, in <module>
    _main_(args)
  File "train.py", line 106, in _main_
    anchors             = config['model']['anchors'])
  File "/home/june/basic-yolo-keras-master/frontend.py", line 48, in __init__
    self.feature_extractor = FullYoloFeature(self.input_size)
  File "/home/june/basic-yolo-keras-master/backend.py", line 157, in __init__
    skip_connection = Lambda(space_to_depth_x2)(skip_connection)
  File "/home/june/anaconda3/envs/junepy27/lib/python2.7/site-packages/keras/engine/topology.py", line 603, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/june/anaconda3/envs/junepy27/lib/python2.7/site-packages/keras/layers/core.py", line 651, in call
    return self.function(inputs, **arguments)
  File "/home/june/basic-yolo-keras-master/backend.py", line 43, in space_to_depth_x2
    return tf.space_to_depth(x, block_size=2)
  File "/home/june/anaconda3/envs/junepy27/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3214, in space_to_depth
    block_size=block_size, name=name)
  File "/home/june/anaconda3/envs/junepy27/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 493, in apply_op
    raise err
TypeError: Expected binary or unicode string, got Elemwise{add,no_inplace}.0
```

**Comment by experiencor** [comment]
@chingjunehao I searched everywhere but found no clue. May I know your Keras and Tensorflow version? My Keras is 2.0.8 and Tensorflow is 1.3.

**Comment by chingjunehao** [comment]
My keras is 2.0.9, tensorflow is:
tensorflow (1.4.1)
tensorflow-gpu (0.12.1)
tensorflow-tensorboard (0.4.0rc3)
Have installed a lower version of theano to use the function in keras, and is in python 2.7.14

**Comment by experiencor** [comment]
@chingjunehao I upgrade to tensorflow 1.4.1 but don't encounter your problem. Please also let me know the commit and the config.json that you are using.

**Comment by chingjunehao** [comment]
python train.py -c config.json

my config.json file is:
```
{
    "model" : {
        "architecture":         "Full Yolo",
        "input_size":           716,
        "anchors":              [1.98, 1.12, 3.20, 1.65, 4.84, 1.77, 7.64, 3.03, 8.85, 5.15],
        "max_box_per_image":    10,        
        "labels":               ["License Plate"]
    },

    "train": {
        "train_image_folder":   "/home/june/basic-yolo-keras-master/train_image_folder/",
        "train_annot_folder":   "/home/june/basic-yolo-keras-master/train_annot_folder/",     
          
        "train_times":          10,
        "pretrained_weights":   "full_yolo_backend.h5",
        "batch_size":           16,
        "learning_rate":        1e-4,
        "nb_epoch":             50,
        "warmup_epochs":        4,

        "object_scale":         5.0 ,
        "no_object_scale":      1.0,
        "coord_scale":          1.0,
        "class_scale":          1.0,

        "saved_weights_name":   "full_yolo_backend.h5",
        "debug":                true
    },

    "valid": {
        "valid_image_folder":   "",
        "valid_annot_folder":   "",

        "valid_times":          1
    }
}
```
even the same when I use full_yolo_raccoon.h5 pretrained weights.

**Comment by experiencor** [comment]
@chingjunehao Ok, I find 2 issues.

1. input_size must be divisible by 32 for FullYolo and TinyYolo.
2. Please read section ```2. Edit the configuration file``` carefully. ```full_yolo_backend.h5``` is only the pre-trained weight for the backend, not the model. You cannot use it like that.

Cheers.

**Comment by chingjunehao** [comment]
I then changed my config file to this:
```
{
    "model" : {
        "architecture":         "Full Yolo",
        "input_size":           416,
        "anchors":              [1.98, 1.12, 3.20, 1.65, 4.84, 1.77, 7.64, 3.03, 8.85, 5.15],
        "max_box_per_image":    10,        
        "labels":               ["License Plate"]
    },

    "train": {
        "train_image_folder":   "/home/june/basic-yolo-keras-master/train_image_folder/",
        "train_annot_folder":   "/home/june/basic-yolo-keras-master/train_annot_folder/",     
          
        "train_times":          10,
        "pretrained_weights":   "full_yolo_raccoon.h5",
        "batch_size":           16,
        "learning_rate":        1e-4,
        "nb_epoch":             50,
        "warmup_epochs":        4,

        "object_scale":         5.0 ,
        "no_object_scale":      1.0,
        "coord_scale":          1.0,
        "class_scale":          1.0,

        "saved_weights_name":   "full_yolo_raccoon.h5",
        "debug":                true
    },

    "valid": {
        "valid_image_folder":   "",
        "valid_annot_folder":   "",

        "valid_times":          1
    }
}
```
But the same error still occurs.
