### ISSUE TITLE
TypeError: Value passed to parameter 'shape' has DataType float32

### ISSUE THREAD

**Issue by HariP1234** [experiencor/basic-yolo-keras#199]
Hi,
I am new to object detection. I believe I installed all dependencies and generated anchors. I am using 416x416 images. I started with 5 images as a trial, but when I start training I get the following error.

Using TensorFlow backend.
Seen labels:     {'num_plate': 5}
Given labels:    ['num_plate']
Overlap labels:  {'num_plate'}
2018-03-22 12:36:49.980078: I C:\tf_jenkins\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
(13, 13)
Traceback (most recent call last):
  File "train.py", line 143, in <module>
    _main_(args)
  File "train.py", line 112, in _main_
    anchors             = config['model']['anchors'])
  File "C:\Users\My book\Desktop\Project\basic-yolo-keras-master\frontend.py", line 67, in __init__
    kernel_initializer='lecun_normal')(features)
  File "C:\ProgramFiles\Anaconda3\lib\site-packages\keras\engine\topology.py", line 592, in __call__
    self.build(input_shapes[0])
  File "C:\ProgramFiles\Anaconda3\lib\site-packages\keras\layers\convolutional.py", line 138, in build
    constraint=self.kernel_constraint)
  File "C:\ProgramFiles\Anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\ProgramFiles\Anaconda3\lib\site-packages\keras\engine\topology.py", line 413, in add_weight
    weight = K.variable(initializer(shape),
  File "C:\ProgramFiles\Anaconda3\lib\site-packages\keras\initializers.py", line 213, in __call__
    dtype=dtype, seed=self.seed)
  File "C:\ProgramFiles\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 3878, in truncated_normal
    return tf.truncated_normal(shape, mean, stddev, dtype=dtype, seed=seed)
  File "C:\ProgramFiles\Anaconda3\lib\site-packages\tensorflow\python\ops\random_ops.py", line 175, in truncated_normal
    shape_tensor, dtype, seed=seed1, seed2=seed2)
  File "C:\ProgramFiles\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_random_ops.py", line 594, in _truncated_normal
    name=name)
  File "C:\ProgramFiles\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 609, in _apply_op_helper
    param_name=input_name)
  File "C:\ProgramFiles\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'shape' has DataType float32 not in list of allowed values: int32, int64

Please somebody help.

**Comment by franksRsrch** [comment]
I got the same error as you using Python 3. I found that I didn't get the error if I used Python 2.7. I'm not sure why.

**Comment by HariP1234** [comment]
I am using Python 2.7. I uninstalled my Python 3.6 and reinstalled Python 2.7

**Comment by franksRsrch** [comment]
That's what happened to me too. I made sure that everything was a fresh install using VirtualEnv and it worked. Maybe worth a try?

**Comment by HariP1234** [comment]
Thank you for the reply. I did as you said. Uninstalled everything and started fresh. But now I cannot install tensorflow using pip or conda. It shows the following error.
UnsatisfiableError: The following specifications were found to be in conflict:
  - python 2.7*
  - tensorflow -> python 3.5*
On searching they say tensorflow is available for python>=3.5. Did this happen to you? What did you do about this?

**Comment by AndyTsangChun** [comment]
Guys, anyway to solve it without switching to 2.7?

**Comment by HariP1234** [comment]
Excuse me AndyTsangChun, but line 27 of which file? And is that the only change required for this project to work in 3.5??

**Comment by AndyTsangChun** [comment]
@HariP1234 
Line 27 of Train.py
And u have to change all of the print to print()
I don't remember anymore changes rn, but just a few of stuff had to change.

**Comment by HariP1234** [comment]
Hi,
I couldn't find that line in Train.py. So I used notepad++ Find in file option. The line was in frontend.py.
I changed that and the print statements. Now getting the IndexError: tuple index out of range error.

**Comment by HariP1234** [comment]
Thats ok. I was able to fix it.

**Comment by AndyTsangChun** [comment]
@HariP1234 
Oh yes my mistake, it should be frontend.py.

**Comment by riri13** [comment]
But which frontend.py file. I am running a python 2.7 file on python 3 version in conda.
