### ISSUE TITLE
AttributeError: Tensor object has no attribute 'assign'

### ISSUE THREAD

**Issue by RyanCodes44** [experiencor/basic-yolo-keras#223]
Hi guys, 

I previously trained the raccoon dataset and everything (for the most part) went smoothly. Now when I try to train my own hand dataset, I received the error mentioned in the title. I saw somewhere that this may be linked to the division by batch size not being equal to a whole number (images/batch_size), but  when working out the math, everything divides well. 

I am using a batch size of 4 for testing purposes, I know this is obviously not ideal.
My Training set consists of 139072 images, validation set 2492 (this is also not ideal).
When I parse annotations, the training and validation set are reduced, but are still divisible by 4. I believe this is because some images do not contain labels? (The labels are "L" for left hand and "R" for right hand)
Also, my .xml annotation files follow the same format as PASCAL VOC labels. 
Therefore, the only real difference between this implementation and what I tried for raccoon is that all images are in the same folder, although I'm not sure this should affect anything.

I don't think this is related to a version issue as I got raccoon working, so I'm not really sure what's wrong. I'm lost :(  **Any Suggestions?** 
 
Tensorflow version: 1.6.0
Keras version: 2.1.3  

**Here is a traceback for when I try left_hand only:** 

```
runfile('M:/Wearable Hand Monitoring/Caffe2Keras Models/basic-yolo-keras-master/train.py', wdir='M:/Wearable Hand Monitoring/Caffe2Keras Models/basic-yolo-keras-master')
Reloaded modules: backend, frontend, preprocessing, utils
Parsing Training
Parsing Validation
Number of training images: 112940
Number of validation images: 1488
Seen labels:     {'L': 112940, 'R': 115954}
Given labels:    ['L']
Overlap labels:  {'L'}
Constructing Model
(13, 13)
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_10 (InputLayer)           (None, 416, 416, 3)  0                                            
__________________________________________________________________________________________________
model_7 (Model)                 (None, 13, 13, 1024) 50547936    input_10[0][0]                   
__________________________________________________________________________________________________
DetectionLayer (Conv2D)         (None, 13, 13, 0)    0           model_7[1][0]                    
__________________________________________________________________________________________________
reshape_4 (Reshape)             (None, 13, 13, 0, 6) 0           DetectionLayer[0][0]             
__________________________________________________________________________________________________
input_11 (InputLayer)           (None, 1, 1, 1, 10,  0                                            
__________________________________________________________________________________________________
lambda_8 (Lambda)               (None, 13, 13, 0, 6) 0           reshape_4[0][0]                  
                                                                 input_11[0][0]                   
==================================================================================================
Total params: 50,547,936
Trainable params: 50,527,264
Non-trainable params: 20,672
__________________________________________________________________________________________________
Training
Traceback (most recent call last):

  File "<ipython-input-17-5edf142e06c2>", line 1, in <module>
    runfile('M:/Caffe2Keras Models/basic-yolo-keras-master/train.py', wdir='M:/Caffe2Keras Models/basic-yolo-keras-master')

  File "C:\Users\vr\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\vr\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "M:/Caffe2Keras Models/basic-yolo-keras-master/train.py", line 127, in <module>
    _main_(config_path)

  File "M:/Caffe2Keras Models/basic-yolo-keras-master/train.py", line 122, in _main_
    debug              = config['train']['debug'])

  File "M:\Caffe2Keras Models\basic-yolo-keras-master\frontend.py", line 336, in train
    max_queue_size   = 8)

  File "C:\Users\vr\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\vr\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\keras\engine\training.py", line 2026, in fit_generator
    self._make_train_function()

  File "C:\Users\vr\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\keras\engine\training.py", line 970, in _make_train_function
    loss=self.total_loss)

  File "C:\Users\vr\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\vr\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\keras\optimizers.py", line 466, in get_updates
    self.updates.append(K.update(m, m_t))

  File "C:\Users\vr\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\keras\backend\tensorflow_backend.py", line 960, in update
    return tf.assign(x, new_x)

  File "C:\Users\vr\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\ops\state_ops.py", line 281, in assign
    return ref.assign(value)

AttributeError: 'Tensor' object has no attribute 'assign'
```

**I tried following along the traceback and printed out 'm' in "get_updates":**

```
<tf.Variable 'training_2/Adam/Variable:0' shape=(3, 3, 3, 32) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_1:0' shape=(32,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_2:0' shape=(32,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_3:0' shape=(3, 3, 32, 64) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_4:0' shape=(64,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_5:0' shape=(64,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_6:0' shape=(3, 3, 64, 128) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_7:0' shape=(128,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_8:0' shape=(128,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_9:0' shape=(1, 1, 128, 64) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_10:0' shape=(64,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_11:0' shape=(64,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_12:0' shape=(3, 3, 64, 128) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_13:0' shape=(128,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_14:0' shape=(128,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_15:0' shape=(3, 3, 128, 256) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_16:0' shape=(256,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_17:0' shape=(256,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_18:0' shape=(1, 1, 256, 128) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_19:0' shape=(128,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_20:0' shape=(128,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_21:0' shape=(3, 3, 128, 256) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_22:0' shape=(256,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_23:0' shape=(256,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_24:0' shape=(3, 3, 256, 512) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_25:0' shape=(512,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_26:0' shape=(512,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_27:0' shape=(1, 1, 512, 256) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_28:0' shape=(256,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_29:0' shape=(256,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_30:0' shape=(3, 3, 256, 512) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_31:0' shape=(512,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_32:0' shape=(512,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_33:0' shape=(1, 1, 512, 256) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_34:0' shape=(256,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_35:0' shape=(256,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_36:0' shape=(3, 3, 256, 512) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_37:0' shape=(512,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_38:0' shape=(512,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_39:0' shape=(3, 3, 512, 1024) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_40:0' shape=(1024,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_41:0' shape=(1024,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_42:0' shape=(1, 1, 1024, 512) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_43:0' shape=(512,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_44:0' shape=(512,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_45:0' shape=(3, 3, 512, 1024) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_46:0' shape=(1024,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_47:0' shape=(1024,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_48:0' shape=(1, 1, 1024, 512) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_49:0' shape=(512,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_50:0' shape=(512,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_51:0' shape=(3, 3, 512, 1024) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_52:0' shape=(1024,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_53:0' shape=(1024,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_54:0' shape=(3, 3, 1024, 1024) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_55:0' shape=(1024,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_56:0' shape=(1024,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_57:0' shape=(1, 1, 512, 64) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_58:0' shape=(64,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_59:0' shape=(64,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_60:0' shape=(3, 3, 1024, 1024) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_61:0' shape=(1024,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_62:0' shape=(1024,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_63:0' shape=(3, 3, 1280, 1024) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_64:0' shape=(1024,) dtype=float32_ref>
<tf.Variable 'training_2/Adam/Variable_65:0' shape=(1024,) dtype=float32_ref>
Tensor("training_2/Adam/zeros_66:0", shape=(1, 1, 1024, 0), dtype=float32)
```
**Also, here is my config file:**
```
{
    "model" : {
        "backend":              "Full Yolo",
        "input_size":           416,
        "anchors":              [],
        "max_box_per_image":    10,        
        "labels":               ["L"]
    },

    "train": {
        "train_image_folder":   "M:/Labelled/hand/J2/RGB405p/",
        "train_annot_folder":   "M:/Caffe2Keras Models/basic-yolo-keras-master/Hand_Data/train/",     
          
        "train_times":          1,
        "pretrained_weights":   "",
        "batch_size":           4,
        "learning_rate":        1e-4,
        "nb_epochs":            50,
        "warmup_epochs":        3,

        "object_scale":         5.0 ,
        "no_object_scale":      1.0,
        "coord_scale":          1.0,
        "class_scale":          1.0,

        "saved_weights_name":   "full_yolo_hand.h5",
        "debug":                true
    },

    "valid": {
        "valid_image_folder":   "M:/Labelled/hand/J2/RGB405p/",
        "valid_annot_folder":   "M:/Caffe2Keras Models/basic-yolo-keras-master/Hand_Data/validation/",

        "valid_times":          1
    }
}
```

**Comment by RyanCodes44** [comment]
Nevermind, it was an issue with the dataset, one of my labmates was messing with me
