### ISSUE TITLE
Issues in training on own dataset

### ISSUE THREAD

**Issue by bhanu223** [experiencor/basic-yolo-keras#43]
I've done some changes to train the model on my own data set.(4 classes). Model architecture is formed and while training epoch 1, the following error is coming:

Epoch 1/100000
Traceback (most recent call last):
  File "train.py", line 137, in <module>
    _main_(args)
  File "train.py", line 133, in _main_
    debug              = config['train']['debug'])
  File "/home/bhanu/Yolo-Keras/frontend.py", line 447, in train
    max_queue_size   = 8)
  File "/usr/local/lib/python3.5/dist-packages/Keras-2.1.1-py3.5.egg/keras/legacy/interfaces.py", line 87, in wrapper
  File "/usr/local/lib/python3.5/dist-packages/Keras-2.1.1-py3.5.egg/keras/engine/training.py", line 2114, in fit_generator
  File "/usr/local/lib/python3.5/dist-packages/Keras-2.1.1-py3.5.egg/keras/engine/training.py", line 1826, in train_on_batch
  File "/usr/local/lib/python3.5/dist-packages/Keras-2.1.1-py3.5.egg/keras/engine/training.py", line 1411, in _standardize_user_data
  File "/usr/local/lib/python3.5/dist-packages/Keras-2.1.1-py3.5.egg/keras/engine/training.py", line 153, in _standardize_input_data
ValueError: Error when checking target: expected lambda_2 to have shape (None, 11, 11, 5, 9) but got array with shape (1, 11, 11, 5, 6)

Please help me with this.

**Comment by experiencor** [comment]
@bhanu223 Would be able to provide the config file and one training example? It's also helpful if can provide the full log.

**Comment by bhanu223** [comment]
Using TensorFlow backend.
{'model': {'anchors': [0.57273, 0.677385, 1.87446, 2.06253, 3.33843, 5.47434, 7.88282, 3.52778, 9.77052, 9.16828], 'architecture': 'Full Yolo', 'input_size': 352, 'max_box_per_image': 10, 'labels': ['car', 'motorbike', 'bus', 'bicycle']}, 'valid': {'valid_times': 1, 'valid_image_folder': '', 'valid_annot_folder': ''}, 'train': {'batch_size': 1, 'nb_epoch': 100000, 'train_image_folder': '/home/bhanu/Yolo-Keras/images/train_image_folder/', 'train_times': 10, 'warmup_batches': 250, 'coord_scale': 1.0, 'saved_weights_name': 'full_yolo_features.h5', 'debug': True, 'pretrained_weights': 'full_yolo_features.h5', 'train_annot_folder': '/home/bhanu/Yolo-Keras/images/train_annot_folder/', 'object_scale': 5.0, 'no_object_scale': 1.0, 'class_scale': 1.0, 'learning_rate': 0.0001}}
/home/bhanu/Yolo-Keras/images/train_annot_folder/
/home/bhanu/Yolo-Keras/images/train_image_folder/
{'bicycle': 1658, 'bus': 1367, 'car': 8095, 'motorbike': 2768}
Full Yolo!!!!!!!!!!!
2017-11-17 11:51:46.838065: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2017-11-17 11:51:47.018716: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-11-17 11:51:47.019710: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:04.0
totalMemory: 11.17GiB freeMemory: 11.09GiB
2017-11-17 11:51:47.019739: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7)
(11, 11)
.....
11
11
.......
(?, 11, 11, 45)
..........
(?, 11, 11, 5, 9)
(?, 11, 11, 5, 9)
............
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_1 (InputLayer)            (None, 352, 352, 3)  0                                            
__________________________________________________________________________________________________
model_1 (Model)                 (None, 11, 11, 1024) 50547936    input_1[0][0]                    
__________________________________________________________________________________________________
conv_23 (Conv2D)                (None, 11, 11, 45)   46125       model_1[1][0]                    
__________________________________________________________________________________________________
reshape_1 (Reshape)             (None, 11, 11, 5, 9) 0           conv_23[0][0]                    
__________________________________________________________________________________________________
input_2 (InputLayer)            (None, 1, 1, 1, 10,  0                                            
__________________________________________________________________________________________________
lambda_2 (Lambda)               (None, 11, 11, 5, 9) 0           reshape_1[0][0]                  
                                                                 input_2[0][0]                    
==================================================================================================
Total params: 50,594,061
Trainable params: 50,573,389
Non-trainable params: 20,672
__________________________________________________________________________________________________
None
<frontend.YOLO object at 0x7f5c7af699b0>
Training started:<preprocessing.BatchGenerator object at 0x7f5c7a30ce48>
Epoch 1/100000
Traceback (most recent call last):
  File "train.py", line 137, in <module>
    _main_(args)
  File "train.py", line 133, in _main_
    debug              = config['train']['debug'])
  File "/home/bhanu/Yolo-Keras/frontend.py", line 447, in train
    max_queue_size   = 8)
  File "/usr/local/lib/python3.5/dist-packages/Keras-2.1.1-py3.5.egg/keras/legacy/interfaces.py", line 87, in wrapper
  File "/usr/local/lib/python3.5/dist-packages/Keras-2.1.1-py3.5.egg/keras/engine/training.py", line 2114, in fit_generator
  File "/usr/local/lib/python3.5/dist-packages/Keras-2.1.1-py3.5.egg/keras/engine/training.py", line 1826, in train_on_batch
  File "/usr/local/lib/python3.5/dist-packages/Keras-2.1.1-py3.5.egg/keras/engine/training.py", line 1411, in _standardize_user_data
  File "/usr/local/lib/python3.5/dist-packages/Keras-2.1.1-py3.5.egg/keras/engine/training.py", line 153, in _standardize_input_data
ValueError: Error when checking target: expected lambda_2 to have shape (None, 11, 11, 5, 9) but got array with shape (1, 11, 11, 5, 6)


Config file:
{
    "model" : {
        "architecture":         "Full Yolo",
        "input_size":           416,
        "anchors":              [0.57273, 0.677385, 1.87446, 2.06253, 3.33843, 5.47434, 7.88282, 3.52778, 9.77052, 9.16828],
        "max_box_per_image":    10,        
        "labels":               ["car","motorbike","bus","bicycle"]
    },

    "train": {
        "train_image_folder":   "/Users/bhanu/Desktop/Yolo-Keras/images/train_image_folder/",
        "train_annot_folder":   "/Users/bhanu/Desktop/Yolo-Keras/images/train_annot_folder/",     
          
        "train_times":          10,
        "pretrained_weights":   "full_yolo_features.h5",
        "batch_size":           50,
        "learning_rate":        1e-4,
        "nb_epoch":             100000,
        "warmup_batches":       250,

        "object_scale":         5.0 ,
        "no_object_scale":      1.0,
        "coord_scale":          1.0,
        "class_scale":          1.0,

        "saved_weights_name":   "full_yolo_features.h5",
        "debug":                true
    },

    "valid": {
        "valid_image_folder":   "",
        "valid_annot_folder":   "",

        "valid_times":          1
    }
}


Training xml:

<annotation><folder>train_image_folder</folder><filename>5564.jpg</filename><source><database>database</database><annotation>annotation</annotation><image>image</image><flickrid>341012865</flickrid></source><owner><flickrid>Fried Camels</flickrid><name>Jinky the Fruit Bat</name></owner><size><width>1280</width><height>960</height><depth>3</depth></size><segmented>0</segmented><object><name>car</name><pose>Unspecified</pose><truncated>0</truncated><difficult>0</difficult><bndbox><xmin>36</xmin><ymin>146</ymin><xmax>347</xmax><ymax>418</ymax></bndbox></object></annotation>

**Comment by bhanu223** [comment]
`
<annotation><folder>train_image_folder</folder><filename>5564.jpg</filename><source><database>database</database><annotation>annotation</annotation><image>image</image><flickrid>341012865</flickrid></source><owner><flickrid>Fried Camels</flickrid><name>Jinky the Fruit Bat</name></owner><size><width>1280</width><height>960</height><depth>3</depth></size><segmented>0</segmented><object><name>car</name><pose>Unspecified</pose><truncated>0</truncated><difficult>0</difficult><bndbox><xmin>36</xmin><ymin>146</ymin><xmax>347</xmax><ymax>418</ymax></bndbox></object></annotation>
`

**Comment by experiencor** [comment]
@bhanu223 May you try to leave "pretrained_weights" and "saved_weights_name" empty? The ***_features.h5 is only for backend, not the full model with the yolo frontend included. It's loaded to the model during model creation.

**Comment by bhanu223** [comment]
@experiencor I've changed it but still getting the same error.

**Comment by experiencor** [comment]
I run your config fine. May you try a fresh pull and run again? I have just updated the code.

**Comment by bhanu223** [comment]
Which file did u update?

**Comment by experiencor** [comment]
I change some logic in reading annotation files recently. It only keeps the images with at least one object class listed in the list of labels. The rest is simply ignored.

**Comment by bhanu223** [comment]
That was taken care by me while loading the images and xml files.

**Comment by experiencor** [comment]
I do this for my personal use. The other difference is that your Keras is 2.1.1 while my Keras is 2.0.8. Any issue with the latest code?

**Comment by bhanu223** [comment]
Only issue is I'm getting the above mentioned error. What should I look for in resolving this kind of errors?

**Comment by experiencor** [comment]
If you try my latest code (I have just updated it) but still got this error, I think it's because of different versions of Keras. I ran your config with the pascal dataset just fine.

**Comment by bhanu223** [comment]
same error is coming again.


Traceback (most recent call last):
  File "train.py", line 99, in <module>
    _main_(args)
  File "train.py", line 95, in _main_
    debug              = config['train']['debug'])
  File "/home/bhanu/Yolo-Keras/frontend.py", line 445, in train
    max_queue_size   = 8)
  File "/usr/local/lib/python3.5/dist-packages/Keras-2.1.1-py3.5.egg/keras/legacy/interfaces.py", line 87, in wrapper
  File "/usr/local/lib/python3.5/dist-packages/Keras-2.1.1-py3.5.egg/keras/engine/training.py", line 2114, in fit_generator
  File "/usr/local/lib/python3.5/dist-packages/Keras-2.1.1-py3.5.egg/keras/engine/training.py", line 1826, in train_on_batch
  File "/usr/local/lib/python3.5/dist-packages/Keras-2.1.1-py3.5.egg/keras/engine/training.py", line 1411, in _standardize_user_data
  File "/usr/local/lib/python3.5/dist-packages/Keras-2.1.1-py3.5.egg/keras/engine/training.py", line 153, in _standardize_input_data
ValueError: Error when checking target: expected lambda_2 to have shape (None, 13, 13, 5, 9) but got array with shape (32, 13, 13, 5, 6)

**Comment by bhanu223** [comment]
How to run this model on multiple gpus?

**Comment by experiencor** [comment]
I use multi_gpu_model in https://keras.io/utils/ in my work. It works great. Probably update the YOLO code with multiple GPUs next week.

**Comment by bhanu223** [comment]
I uninstalled the latest Keras version and reinstalled 2.0.8 and it worked for me.
