### ISSUE TITLE
No module named expat; use SimpleXMLTreeBuilder instead error

### ISSUE THREAD

**Issue by jcgarciaca** [experiencor/basic-yolo-keras#69]
Hi,
When I run `python train.py -c config.json`. The following error appears:

```
Using TensorFlow backend.
Traceback (most recent call last):
  File "train.py", line 140, in <module>
    _main_(args)
  File "train.py", line 76, in _main_
    config['model']['labels'])
  File "/home/julio_jcgc/yolo_tutorial/basic-yolo-keras/preprocessing.py", line 21, in parse_annotation
    tree = ET.parse(ann_dir + ann)
  File "/opt/bitnami/python/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/opt/bitnami/python/lib/python2.7/xml/etree/ElementTree.py", line 651, in parse
    parser = XMLParser(target=TreeBuilder())
  File "/opt/bitnami/python/lib/python2.7/xml/etree/ElementTree.py", line 1476, in __init__
    "No module named expat; use SimpleXMLTreeBuilder instead"
ImportError: No module named expat; use SimpleXMLTreeBuilder instead
```
Thank you.

**Comment by experiencor** [comment]
@jcgarciaca I have never encountered this issue. Check this out https://stackoverflow.com/questions/1068510/using-simplexmltreebuilder-in-elementtree.

**Comment by jcgarciaca** [comment]
@experiencor I don't know why the error appears, I just changed to python3 and it solved this issue.
However when training the following message is shown:

```
Total params: 50,578,686
Trainable params: 50,558,014
Non-trainable params: 20,672
_________________________________________________
Loading pre-trained weights in full_yolo_raccoon.h5
Traceback (most recent call last):
  File "train.py", line 140, in <module>
    _main_(args)
  File "train.py", line 136, in _main_
    debug              = config['train']['debug'])
  File "/mnt/disks/disk1-500/yolo_tutorial/basic-yolo-keras/frontend.py", line 432, in train
    write_images=False)
TypeError: __init__() got an unexpected keyword argument 'write_batch_performance'
```
I commented the line `write_batch_performance=True,` and it worked. Do you think it is OK?

Finally, I am trying to train with my own data but I have a doubt. My XML files include an entry `<folder>/datos/marketteam/data/Images/SKU600</folder>` is it supposed my images should be inside this folder?

Thank you

**Comment by experiencor** [comment]
Yes, it's okay to comment out ```write_batch_performance=True```. It's used in the development version of Keras.
The images should be stored in the additional folder according to with config.json settings.

**Comment by jcgarciaca** [comment]
Thank you for your answer.
Sorry, I have an extra doubt. When training with my own data 

```
Loading pre-trained weights in full_yolo_raccoon.h5
Traceback (most recent call last):
  File "train.py", line 140, in <module>
    _main_(args)
  File "train.py", line 117, in _main_
    yolo.load_weights(config['train']['pretrained_weights'])
  File "/mnt/disks/disk1-500/Praxis/basic-yolo-keras/frontend.py", line 239, in load_weights
    self.model.load_weights(weight_path)
  File "/usr/local/lib/python3.4/dist-packages/keras/engine/topology.py", line 2622, in load_weights
    load_weights_from_hdf5_group(f, self.layers)
  File "/usr/local/lib/python3.4/dist-packages/keras/engine/topology.py", line 3143, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/usr/local/lib/python3.4/dist-packages/keras/backend/tensorflow_backend.py", line 2252, in batch_set_value
    get_session().run(assign_ops, feed_dict=feed_dict)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 1096, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (30, 1024, 1, 1) for Tensor 'Placeholder_110:0', which has shape '(1, 1, 1024, 95)'
```

I noted my current network architecture is

```
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_1 (InputLayer)            (None, 416, 416, 3)  0                                            
__________________________________________________________________________________________________
model_1 (Model)                 (None, 13, 13, 1024) 50547936    input_1[0][0]                    
__________________________________________________________________________________________________
conv_23 (Conv2D)                (None, 13, 13, 95)   97375       model_1[1][0]                    
__________________________________________________________________________________________________
reshape_1 (Reshape)             (None, 13, 13, 5, 19 0           conv_23[0][0]                    
__________________________________________________________________________________________________
input_2 (InputLayer)            (None, 1, 1, 1, 50,  0                                            
__________________________________________________________________________________________________
lambda_2 (Lambda)               (None, 13, 13, 5, 19 0           reshape_1[0][0]                  
                                                                 input_2[0][0]                    
==================================================================================================
Total params: 50,645,311
Trainable params: 50,624,639
Non-trainable params: 20,672
```


But actually the architecture I get when using raccoon example is:

```
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_1 (InputLayer)            (None, 416, 416, 3)  0                                            
__________________________________________________________________________________________________
model_1 (Model)                 (None, 13, 13, 1024) 50547936    input_1[0][0]                    
__________________________________________________________________________________________________
conv_23 (Conv2D)                (None, 13, 13, 30)   30750       model_1[1][0]                    
__________________________________________________________________________________________________
reshape_1 (Reshape)             (None, 13, 13, 5, 6) 0           conv_23[0][0]                    
__________________________________________________________________________________________________
input_2 (InputLayer)            (None, 1, 1, 1, 10,  0                                            
__________________________________________________________________________________________________
lambda_2 (Lambda)               (None, 13, 13, 5, 6) 0           reshape_1[0][0]                  
                                                                 input_2[0][0]                    
==================================================================================================
Total params: 50,578,686
Trainable params: 50,558,014
Non-trainable params: 20,672
```

In `conv_23 (Conv2D)` original layer has shape `(None, 13, 13, 30)`, but in my case it is `(None, 13, 13, 95)`. I suppose it is the reason why weights are not loaded. Do you know what I could do? Should I train from scratch?

Thank you.

**Comment by jcgarciaca** [comment]
I noted some objects inside XML file don't have `xmin` tag.
I am trying to edit [https://github.com/experiencor/basic-yolo-keras/blob/f5ded225c6ee5e7d69a76a466cde0e1ec1e79e58/preprocessing.py#L267](url) to check if object has the tag, but I am not sure how to do it yet.

**Comment by experiencor** [comment]
@jcgarciaca Hope you resolved the xmin issue. I would suggest you clean the dataset first before changing the code of YOLO.

Meaning of prevalent: if the bounding boxes in your dataset have different sizes but most of them are very near to either (10, 5) or (3, 4), you can use these two sizes as two anchors. Think about clustering. If you plot the sizes on a 2D graph, they would cluster around two centers. These two centers are very good candidates for anchors.

**Comment by jcgarciaca** [comment]
@experiencor
Thank you. I edited the XML dataset and it seems to run properly (although it takes a lot of time).

I want to clarify something.

In **Warm up the network** I don't load pretrained_weights (`"pretrained_weights": ""` in `config.json`) with using `"warmup_epochs": 3`. When finishing this process does it save the weights according with `"saved_weights_name": "best_weights.h5"` (`best_weights.h5` doesn't exist initially)? If doesn't, what is the result in this process?

Then for **Actual Network Training** I would set `"warmup_epochs": 0`. And should I set `"pretrained_weights": "`best_weights.h5"` in previous step?

Thank you.

**Comment by experiencor** [comment]
@jcgarciaca If ```"pretrained_weights"``` is not specified, the default ```"pretrained_weights"``` is ```best_weights.h5```.

You should set ```"pretrained_weights": "best_weights.h5"```. It will start the actual training from this weight. Otherwise, it will start from scratch.

**Comment by jcgarciaca** [comment]
@experiencor 
Thank you. I am training the network with my data. I tell you how it is going.

**Comment by jcgarciaca** [comment]
Hi @experiencor 
I have a doubt. 
I run the warming up for 3 epochs and noted in general `Total Loss` value decreased from around 2.8 to 0.1. By the end of this process I tested the model with `best_weights` generated file to predict some images in my training dataset. Nevertheless, the results are **0 boxes found**. Is it normal?
Anyway, I started the training stage with `"pretrained_weights": "best_weights.h5"` and reduced by ten the `learning_rate` param. But I am not sure if my network is actually learning. Below a piece of my output

```
156/330 [=============>................] - ETA: 3:25:03 - loss: 0.95022017-12-08 16:02:09.540872: I tensorflow/core/kernels/logging_ops.cc:79] Dummy Line       [0]
2017-12-08 16:02:09.540918: I tensorflow/core/kernels/logging_ops.cc:79] Loss XY        [0.0800739229]
2017-12-08 16:02:09.540929: I tensorflow/core/kernels/logging_ops.cc:79] Loss WH        [0.410522878]
2017-12-08 16:02:09.540938: I tensorflow/core/kernels/logging_ops.cc:79] Loss Conf      [0.00301904907]
2017-12-08 16:02:09.540947: I tensorflow/core/kernels/logging_ops.cc:79] Loss Class     [0.0774360448]
2017-12-08 16:02:09.540956: I tensorflow/core/kernels/logging_ops.cc:79] Total Loss     [0.571051896]
2017-12-08 16:02:09.540964: I tensorflow/core/kernels/logging_ops.cc:79] Current Recall         [0]
157/330 [=============>................] - ETA: 3:23:51 - loss: 0.94782017-12-08 16:03:19.054387: I tensorflow/core/kernels/logging_ops.cc:79] Dummy Line       [0]
2017-12-08 16:03:19.054431: I tensorflow/core/kernels/logging_ops.cc:79] Loss XY        [0.0689806193]
2017-12-08 16:03:19.054442: I tensorflow/core/kernels/logging_ops.cc:79] Loss WH        [0.33346352]
2017-12-08 16:03:19.054451: I tensorflow/core/kernels/logging_ops.cc:79] Loss Conf      [0.00255710282]
2017-12-08 16:03:19.054463: I tensorflow/core/kernels/logging_ops.cc:79] Loss Class     [0.0993253663]
2017-12-08 16:03:19.054472: I tensorflow/core/kernels/logging_ops.cc:79] Total Loss     [0.504326582]
2017-12-08 16:03:19.054480: I tensorflow/core/kernels/logging_ops.cc:79] Current Recall         [0]
158/330 [=============>................] - ETA: 3:22:40 - loss: 0.94502017-12-08 16:04:28.701718: I tensorflow/core/kernels/logging_ops.cc:79] Dummy Line       [0]
2017-12-08 16:04:28.701760: I tensorflow/core/kernels/logging_ops.cc:79] Loss XY        [0.0762655213]
2017-12-08 16:04:28.701772: I tensorflow/core/kernels/logging_ops.cc:79] Loss WH        [0.515747547]
2017-12-08 16:04:28.701782: I tensorflow/core/kernels/logging_ops.cc:79] Loss Conf      [0.00213015499]
2017-12-08 16:04:28.701790: I tensorflow/core/kernels/logging_ops.cc:79] Loss Class     [0.0294866804]
2017-12-08 16:04:28.701799: I tensorflow/core/kernels/logging_ops.cc:79] Total Loss     [0.623629868]
2017-12-08 16:04:28.701807: I tensorflow/core/kernels/logging_ops.cc:79] Current Recall         [0]
2017-12-08 16:04:28.701816: I tensorflow/core/kernels/logging_ops.cc:79] Average Recall         [0]
159/330 [=============>................] - ETA: 3:21:28 - loss: 0.94302017-12-08 16:05:38.597365: I tensorflow/core/kernels/logging_ops.cc:79] Dummy Line       [0]
2017-12-08 16:05:38.597404: I tensorflow/core/kernels/logging_ops.cc:79] Loss XY        [0.0879120454]
2017-12-08 16:05:38.597415: I tensorflow/core/kernels/logging_ops.cc:79] Loss WH        [0.340136617]
2017-12-08 16:05:38.597425: I tensorflow/core/kernels/logging_ops.cc:79] Loss Conf      [0.00266033178]
2017-12-08 16:05:38.597434: I tensorflow/core/kernels/logging_ops.cc:79] Loss Class     [0.064822562]
2017-12-08 16:05:38.597444: I tensorflow/core/kernels/logging_ops.cc:79] Total Loss     [0.495531559]
2017-12-08 16:05:38.597451: I tensorflow/core/kernels/logging_ops.cc:79] Current Recall         [0]
160/330 [=============>................] - ETA: 3:20:16 - loss: 0.94022017-12-08 16:06:48.177147: I tensorflow/core/kernels/logging_ops.cc:79] Dummy Line       [0]
2017-12-08 16:06:48.177190: I tensorflow/core/kernels/logging_ops.cc:79] Loss XY        [0.0993975475]
2017-12-08 16:06:48.177202: I tensorflow/core/kernels/logging_ops.cc:79] Loss WH        [0.771403849]
2017-12-08 16:06:48.177211: I tensorflow/core/kernels/logging_ops.cc:79] Loss Conf      [0.0019874007]
2017-12-08 16:06:48.177220: I tensorflow/core/kernels/logging_ops.cc:79] Loss Class     [0.301772952]
2017-12-08 16:06:48.177230: I tensorflow/core/kernels/logging_ops.cc:79] Total Loss     [1.17456174]
2017-12-08 16:06:48.177238: I tensorflow/core/kernels/logging_ops.cc:79] Current Recall         [0]
2017-12-08 16:06:48.177245: I tensorflow/core/kernels/logging_ops.cc:79] Average Recall         [0]
161/330 [=============>................] - ETA: 3:19:04 - loss: 0.94162017-12-08 16:07:57.697530: I tensorflow/core/kernels/logging_ops.cc:79] Dummy Line       [0]
2017-12-08 16:07:57.697574: I tensorflow/core/kernels/logging_ops.cc:79] Loss XY        [0.0742812604]
2017-12-08 16:07:57.697585: I tensorflow/core/kernels/logging_ops.cc:79] Loss WH        [0.398485571]
2017-12-08 16:07:57.697594: I tensorflow/core/kernels/logging_ops.cc:79] Loss Conf      [0.00261747907]
2017-12-08 16:07:57.697603: I tensorflow/core/kernels/logging_ops.cc:79] Loss Class     [0.0222724825]
2017-12-08 16:07:57.697612: I tensorflow/core/kernels/logging_ops.cc:79] Total Loss     [0.497656763]
2017-12-08 16:07:57.697620: I tensorflow/core/kernels/logging_ops.cc:79] Current Recall         [0]
2017-12-08 16:07:57.697630: I tensorflow/core/kernels/logging_ops.cc:79] Average Recall         [0]
162/330 [=============>................] - ETA: 3:17:53 - loss: 0.93892017-12-08 16:09:07.544916: I tensorflow/core/kernels/logging_ops.cc:79] Dummy Line       [0]
2017-12-08 16:09:07.544960: I tensorflow/core/kernels/logging_ops.cc:79] Loss XY        [0.0787630677]
2017-12-08 16:09:07.544972: I tensorflow/core/kernels/logging_ops.cc:79] Loss WH        [0.342845589]
2017-12-08 16:09:07.544981: I tensorflow/core/kernels/logging_ops.cc:79] Loss Conf      [0.00240920577]
2017-12-08 16:09:07.544989: I tensorflow/core/kernels/logging_ops.cc:79] Loss Class     [0.0483088419]
2017-12-08 16:09:07.544998: I tensorflow/core/kernels/logging_ops.cc:79] Total Loss     [0.472326726]
2017-12-08 16:09:07.545006: I tensorflow/core/kernels/logging_ops.cc:79] Current Recall         [0]
2017-12-08 16:09:07.545013: I tensorflow/core/kernels/logging_ops.cc:79] Average Recall         [0]
163/330 [=============>................] - ETA: 3:16:41 - loss: 0.93602017-12-08 16:10:17.202009: I tensorflow/core/kernels/logging_ops.cc:79] Dummy Line       [0]
2017-12-08 16:10:17.202072: I tensorflow/core/kernels/logging_ops.cc:79] Loss XY        [0.0732013285]
2017-12-08 16:10:17.202084: I tensorflow/core/kernels/logging_ops.cc:79] Loss WH        [0.267014623]
2017-12-08 16:10:17.202094: I tensorflow/core/kernels/logging_ops.cc:79] Loss Conf      [0.00288054254]
2017-12-08 16:10:17.202103: I tensorflow/core/kernels/logging_ops.cc:79] Loss Class     [0.155185953]
2017-12-08 16:10:17.202111: I tensorflow/core/kernels/logging_ops.cc:79] Total Loss     [0.498282433]
2017-12-08 16:10:17.202120: I tensorflow/core/kernels/logging_ops.cc:79] Current Recall         [0]
2017-12-08 16:10:17.202128: I tensorflow/core/kernels/logging_ops.cc:79] Average Recall         [0]
...
2017-12-08 16:26:50.156884: I tensorflow/core/kernels/logging_ops.cc:79] Dummy Line     [0]
2017-12-08 16:26:50.156928: I tensorflow/core/kernels/logging_ops.cc:79] Loss XY        [0.0884088948]
2017-12-08 16:26:50.156939: I tensorflow/core/kernels/logging_ops.cc:79] Loss WH        [0.275535882]
2017-12-08 16:26:50.156948: I tensorflow/core/kernels/logging_ops.cc:79] Loss Conf      [0.00254791067]
2017-12-08 16:26:50.156957: I tensorflow/core/kernels/logging_ops.cc:79] Loss Class     [0.0154163856]
2017-12-08 16:26:50.156966: I tensorflow/core/kernels/logging_ops.cc:79] Total Loss     [0.381909072]
2017-12-08 16:26:50.156974: I tensorflow/core/kernels/logging_ops.cc:79] Current Recall         [0]
178/330 [===============>..............] - ETA: 2:59:03 - loss: 0.9005
2017-12-08 16:28:00.705855: I tensorflow/core/kernels/logging_ops.cc:79] Dummy Line     [0]
2017-12-08 16:28:00.705899: I tensorflow/core/kernels/logging_ops.cc:79] Loss XY        [0.0903893]
2017-12-08 16:28:00.705911: I tensorflow/core/kernels/logging_ops.cc:79] Loss WH        [0.240427911]
2017-12-08 16:28:00.705920: I tensorflow/core/kernels/logging_ops.cc:79] Loss Conf      [0.00215155887]
2017-12-08 16:28:00.705929: I tensorflow/core/kernels/logging_ops.cc:79] Loss Class     [0.0350015312]
2017-12-08 16:28:00.705938: I tensorflow/core/kernels/logging_ops.cc:79] Total Loss     [0.367970288]
2017-12-08 16:28:00.705946: I tensorflow/core/kernels/logging_ops.cc:79] Current Recall         [0]
179/330 [===============>..............] - ETA: 2:57:52 - loss: 0.8975
...
2017-12-08 16:33:53.312021: I tensorflow/core/kernels/logging_ops.cc:79] Dummy Line     [0]
2017-12-08 16:33:53.312079: I tensorflow/core/kernels/logging_ops.cc:79] Loss XY        [0.0863895938]
2017-12-08 16:33:53.312090: I tensorflow/core/kernels/logging_ops.cc:79] Loss WH        [0.497869909]
2017-12-08 16:33:53.312100: I tensorflow/core/kernels/logging_ops.cc:79] Loss Conf      [0.00248469785]
2017-12-08 16:33:53.312108: I tensorflow/core/kernels/logging_ops.cc:79] Loss Class     [0.0237709247]
2017-12-08 16:33:53.312119: I tensorflow/core/kernels/logging_ops.cc:79] Total Loss     [0.610515118]
2017-12-08 16:33:53.312128: I tensorflow/core/kernels/logging_ops.cc:79] Current Recall         [0]
184/330 [===============>..............] - ETA: 2:51:59 - loss: 0.8870
2017-12-08 16:35:04.137791: I tensorflow/core/kernels/logging_ops.cc:79] Dummy Line     [0]
2017-12-08 16:35:04.137833: I tensorflow/core/kernels/logging_ops.cc:79] Loss XY        [0.0840129703]
2017-12-08 16:35:04.137843: I tensorflow/core/kernels/logging_ops.cc:79] Loss WH        [0.821007788]
2017-12-08 16:35:04.137852: I tensorflow/core/kernels/logging_ops.cc:79] Loss Conf      [0.0025500746]
2017-12-08 16:35:04.137862: I tensorflow/core/kernels/logging_ops.cc:79] Loss Class     [0.0621787347]
2017-12-08 16:35:04.137871: I tensorflow/core/kernels/logging_ops.cc:79] Total Loss     [0.96974957]
2017-12-08 16:35:04.137879: I tensorflow/core/kernels/logging_ops.cc:79] Current Recall         [0]
185/330 [===============>..............] - ETA: 2:50:48 - loss: 0.8874
...
2017-12-08 16:38:35.619677: I tensorflow/core/kernels/logging_ops.cc:79] Dummy Line     [0]
2017-12-08 16:38:35.619725: I tensorflow/core/kernels/logging_ops.cc:79] Loss XY        [0.0880509615]
2017-12-08 16:38:35.619735: I tensorflow/core/kernels/logging_ops.cc:79] Loss WH        [0.40031293]
2017-12-08 16:38:35.619745: I tensorflow/core/kernels/logging_ops.cc:79] Loss Conf      [0.00270356587]
2017-12-08 16:38:35.619754: I tensorflow/core/kernels/logging_ops.cc:79] Loss Class     [0.0458568446]
2017-12-08 16:38:35.619763: I tensorflow/core/kernels/logging_ops.cc:79] Total Loss     [0.536924303]
2017-12-08 16:38:35.619771: I tensorflow/core/kernels/logging_ops.cc:79] Current Recall         [0]
188/330 [================>.............] - ETA: 2:47:15 - loss: 0.8806
2017-12-08 16:39:46.338258: I tensorflow/core/kernels/logging_ops.cc:79] Dummy Line     [0]
2017-12-08 16:39:46.338302: I tensorflow/core/kernels/logging_ops.cc:79] Loss XY        [0.080215849]
2017-12-08 16:39:46.338314: I tensorflow/core/kernels/logging_ops.cc:79] Loss WH        [0.293333083]
2017-12-08 16:39:46.338323: I tensorflow/core/kernels/logging_ops.cc:79] Loss Conf      [0.00290440302]
2017-12-08 16:39:46.338331: I tensorflow/core/kernels/logging_ops.cc:79] Loss Class     [0.019609971]
2017-12-08 16:39:46.338340: I tensorflow/core/kernels/logging_ops.cc:79] Total Loss     [0.396063298]
2017-12-08 16:39:46.338348: I tensorflow/core/kernels/logging_ops.cc:79] Current Recall         [0]
189/330 [================>.............] - ETA: 2:46:05 - loss: 0.87802017-12-08 16:40:56.305727: I tensorflow/core/kernels/logging_ops.cc:79] Dummy Line       [0]
2017-12-08 16:40:56.305773: I tensorflow/core/kernels/logging_ops.cc:79] Loss XY        [0.0754767656]
2017-12-08 16:40:56.305783: I tensorflow/core/kernels/logging_ops.cc:79] Loss WH        [0.258777052]
2017-12-08 16:40:56.305792: I tensorflow/core/kernels/logging_ops.cc:79] Loss Conf      [0.00246067625]
2017-12-08 16:40:56.305801: I tensorflow/core/kernels/logging_ops.cc:79] Loss Class     [0.0148462038]
2017-12-08 16:40:56.305810: I tensorflow/core/kernels/logging_ops.cc:79] Total Loss     [0.351560712]
2017-12-08 16:40:56.305819: I tensorflow/core/kernels/logging_ops.cc:79] Current Recall         [0]
2017-12-08 16:40:56.305826: I tensorflow/core/kernels/logging_ops.cc:79] Average Recall         [0]
190/330 [================>.............] - ETA: 2:44:53 - loss: 0.87529
```
`Total Loss` reduces and increases although `loss` is continuously decreasing. Is this process OK?

Thank you.

**Comment by jcgarciaca** [comment]
When first epoch ends it tries to save the best_weights file, but for any reason an error appears. I check permissions in .h5 file and it has actually rw permissions for all users.

```
Epoch 00001: val_loss improved from inf to 0.27091, saving model to best_weights.h5
Traceback (most recent call last):
  File "train.py", line 140, in <module>
    _main_(args)
  File "train.py", line 136, in _main_
    debug              = config['train']['debug'])
  File "/mnt/disks/disk1-500/Praxis/basic-yolo-keras/frontend.py", line 448, in train
    max_queue_size   = 8)
  File "/usr/local/lib/python3.4/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/keras/engine/training.py", line 2187, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/local/lib/python3.4/dist-packages/keras/callbacks.py", line 73, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/usr/local/lib/python3.4/dist-packages/keras/callbacks.py", line 415, in on_epoch_end
    self.model.save(filepath, overwrite=True)
  File "/usr/local/lib/python3.4/dist-packages/keras/engine/topology.py", line 2556, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "/usr/local/lib/python3.4/dist-packages/keras/models.py", line 103, in save_model
    with h5py.File(filepath, mode='w') as f:
  File "/usr/lib/python3/dist-packages/h5py/_hl/files.py", line 206, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/usr/lib/python3/dist-packages/h5py/_hl/files.py", line 85, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5f.pyx", line 90, in h5py.h5f.create (h5py/h5f.c:1986)
OSError: unable to create file (File accessibilty: Unable to open file)
```
I am running the training again from scratch (and deleted .h5 file created in warming). Here the loss value started in 5. I hope it works.

**Comment by experiencor** [comment]
Hi @jcgarciaca How's your result?

**Comment by jcgarciaca** [comment]
@experiencor 
I am still in training, as my previous message the loss value started around 5, by now in 4th epoch it is 0.738. I would suppose the process is running well. Any comment?

**Comment by experiencor** [comment]
@jcgarciaca The performance varies and depends on a lot of factors like the used model, the scales, and learning rate. I suggest you use Full Yolo for best performance. For others, you may need to tune the 4 scales to make them work.

**Comment by jcgarciaca** [comment]
Hi @experiencor 
Currently the process is in 8th epoch and loss value in 0.225. Thank you for your help, I use Full Yolo model. I'll wait if it continues decreasing.

**Comment by jcgarciaca** [comment]
In 9th epoch I get `loss: 0.1894 - val_loss: 0.3735`. I tested with a training image but still get
```
best_weights.h5
0 boxes are found
OpenCV Error: Unspecified error (could not find a writer for the specified extension) in imwrite_, file /home/julio_jcgc/OpenCV-tmp/opencv-3/modules/imgcodecs/src/loadsave.cpp, line 677
Traceback (most recent call last):
  File "predict.py", line 99, in <module>
    _main_(args)
  File "predict.py", line 95, in _main_
    cv2.imwrite(image_path[:-4] + '_detected' + image_path[-4:], image)
cv2.error: /home/julio_jcgc/OpenCV-tmp/opencv-3/modules/imgcodecs/src/loadsave.cpp:677: error: (-2) could not find a writer for the specified extension in function imwrite_

Exception ignored in: <bound method Session.__del__ of <tensorflow.python.client.session.Session object at 0x7f0eec1007b8>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 696, in __del__
TypeError: 'NoneType' object is not callable
```

**Comment by tuan2061996** [comment]
Traceback (most recent call last):
  File "train.py", line 99, in <module>
    _main_(args)
  File "train.py", line 95, in _main_
    debug              = config['train']['debug'])
  File "/home/pooh/yolo/frontend.py", line 432, in train
    write_images=False)
TypeError: __init__() got an unexpected keyword argument 'write_batch_performance'

i try like @jcgarciaca but not working
can you help me? pls

**Comment by jcgarciaca** [comment]
@tuan2061996 
Did you comment `write_batch_performance=True` in `frontend.py`?
