### ISSUE TITLE
StopIteration: 'filename'

### ISSUE THREAD

**Issue by roccolocko** [experiencor/basic-yolo-keras#76]
Hello @experiencor 
I'm getting the following error:
```
Using TensorFlow backend.
('Seen labels:\t', {'skirt': 14773, 'sweater': 13123, 'blazer': 7495, 'tee': 36887})
('Given labels:\t', [u'blazer', u'tee', u'sweater', u'skirt'])
('Overlap labels:\t', set(['skirt', 'sweater', 'blazer', 'tee']))
2017-12-07 05:07:59.638381: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
(13, 13)
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to
==================================================================================================
input_1 (InputLayer)            (None, 416, 416, 3)  0
__________________________________________________________________________________________________
model_1 (Model)                 (None, 13, 13, 1024) 50547936    input_1[0][0]
__________________________________________________________________________________________________
conv_23 (Conv2D)                (None, 13, 13, 45)   46125       model_1[1][0]
__________________________________________________________________________________________________
reshape_1 (Reshape)             (None, 13, 13, 5, 9) 0           conv_23[0][0]
__________________________________________________________________________________________________
input_2 (InputLayer)            (None, 1, 1, 1, 10,  0
__________________________________________________________________________________________________
lambda_2 (Lambda)               (None, 13, 13, 5, 9) 0           reshape_1[0][0]
                                                                 input_2[0][0]
==================================================================================================
Total params: 50,594,061
Trainable params: 50,573,389
Non-trainable params: 20,672
__________________________________________________________________________________________________
Epoch 1/3
Traceback (most recent call last):
  File "train.py", line 140, in <module>
    _main_(args)
  File "train.py", line 136, in _main_
    debug              = config['train']['debug'])
  File "/home/erika_rodriguez/basic-yolo-keras-master/frontend.py", line 446, in train
    max_queue_size   = 8)
  File "/usr/lib64/python2.7/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/keras/engine/training.py", line 2115, in fit_generator
    generator_output = next(output_generator)
  File "/usr/lib64/python2.7/site-packages/keras/utils/data_utils.py", line 557, in get
    six.raise_from(StopIteration(e), e)
  File "/usr/lib/python2.7/site-packages/six.py", line 737, in raise_from
    raise value
StopIteration: 'filename'
```

So far I just modified (commented) the line 430 on the frontend.py file:
`                                  #write_batch_performance=True,`

My config file looks like this:
```
{
    "model" : {
        "architecture":         "Full Yolo",
        "input_size":           416,
        "anchors":              [0.57273, 0.677385, 1.87446, 2.06253, 3.33843, 5.47434, 7.88282, 3.52778, 9.77052, 9.16828],
        "max_box_per_image":    10,        
        "labels":               ["blazer","tee","sweater","skirt"]
    },

    "train": {
        "train_image_folder":   "/home/erika_rodriguez/img/",
        "train_annot_folder":   "/home/erika_rodriguez/annotations/",     
          
        "train_times":          10,
        "pretrained_weights":   "",
        "batch_size":           16,
        "learning_rate":        1e-4,
        "nb_epoch":             50,
        "warmup_epochs":        3,

        "object_scale":         5.0 ,
        "no_object_scale":      1.0,
        "coord_scale":          1.0,
        "class_scale":          1.0,

        "saved_weights_name":   "full_yolo_cloths.h5",
        "debug":                true
    },

    "valid": {
        "valid_image_folder":   "/home/erika_rodriguez/valid/img/",
        "valid_annot_folder":   "/home/erika_rodriguez/valid/annotations/",

        "valid_times":          1
    }
}
```
I would really appreciate if you could give me a hint about what could be happening...
Thanx.

**Comment by roccolocko** [comment]
The problem was in the generated VOC. I put by mistake "file" instead of "filename".
