### ISSUE TITLE
Error at the end of first epoch

### ISSUE THREAD

**Issue by bhavindhedhi** [experiencor/basic-yolo-keras#79]
Traceback (most recent call last):
  File "C:\Users\DELL\Anaconda3\envs\tensorflow\lib\site-packages\keras\utils\data_utils.py", line 551, in get
    inputs = self.queue.get(block=True).get()
  File "C:\Users\DELL\Anaconda3\envs\tensorflow\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
  File "C:\Users\DELL\Anaconda3\envs\tensorflow\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\DELL\Anaconda3\envs\tensorflow\lib\site-packages\keras\utils\data_utils.py", line 391, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "E:\Bhavin\basic-yolo-keras-master\basic-yolo-keras-master\preprocessing.py", line 157, in __getitem__
    img, all_objs = self.aug_image(train_instance, jitter=self.jitter)
  File "E:\Bhavin\basic-yolo-keras-master\basic-yolo-keras-master\preprocessing.py", line 238, in aug_image
    h, w, c = image.shape
AttributeError: 'NoneType' object has no attribute 'shape'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 101, in <module>
    _main_(args)
  File "train.py", line 97, in _main_
    debug              = config['train']['debug'])
  File "E:\Bhavin\basic-yolo-keras-master\basic-yolo-keras-master\frontend.py", line 445, in train
    max_queue_size   = 8)
  File "C:\Users\DELL\Anaconda3\envs\tensorflow\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\DELL\Anaconda3\envs\tensorflow\lib\site-packages\keras\engine\training.py", line 2169, in fit_generator
    use_multiprocessing=use_multiprocessing)
  File "C:\Users\DELL\Anaconda3\envs\tensorflow\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\DELL\Anaconda3\envs\tensorflow\lib\site-packages\keras\engine\training.py", line 2280, in evaluate_generator
    generator_output = next(output_generator)
  File "C:\Users\DELL\Anaconda3\envs\tensorflow\lib\site-packages\keras\utils\data_utils.py", line 557, in get
    six.raise_from(StopIteration(e), e)
  File "<string>", line 2, in raise_from
StopIteration: 'NoneType' object has no attribute 'shape'

**Comment by experiencor** [comment]
@bhavindhedhi This error is most likely caused by wrongly named image files. You have to make sure that the name of the image file specified in the XML file matches the actual file name. Best to use the notebook ```Yolo Step-by-Step.ipynb``` to debug.

**Comment by bhavindhedhi** [comment]
quick update, I solved the error by changing following:
from:
`if os.path.exists(config['valid']['valid_annot_folder']):`
to:
`if os.path.exists(r"config['valid']['valid_annot_folder']"):`

and
from:
`if os.path.exists(config['train']['pretrained_weights']):`
to:
`if os.path.exists(r"config['train']['pretrained_weights']"):`
