### ISSUE TITLE
Can't train on raccoon images

### ISSUE THREAD

**Issue by srconstantin** [experiencor/basic-yolo-keras#93]
When I give the command 
`python train.py -c config.json`

I get the following error:

`Traceback (most recent call last):
  File "train.py", line 102, in <module>
    _main_(args)
  File "train.py", line 98, in _main_
    debug              = config['train']['debug'])
  File "/home/sarah/objectdetection3/basic-yolo-keras/frontend.py", line 445, in train
    max_queue_size   = 8)
  File "/home/sarah/anaconda2/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/sarah/anaconda2/lib/python2.7/site-packages/keras/engine/training.py", line 2011, in fit_generator
    generator_output = next(output_generator)e
  File "/home/sarah/anaconda2/lib/python2.7/site-packages/keras/utils/data_utils.py", line 510, in get
    raise StopIteration(e)
StopIteration: 'NoneType' object has no attribute 'shape'
sarah@starship:~/objectdetection3/basic-yolo-keras$ python tr`

I'm using your version of the raccoon dataset where the xml paths and the images are both jpgs and I've tested with cv2 that all the raccoon image files will open. The YOLO Step By Step notebook runs fine.  So I'm still not sure what the problem is.

**Comment by experiencor** [comment]
@srconstantin This error happens all the time and the single reason is that users have failed to set the image and annotation directory correctly. You may want to look into that.

**Comment by ashah03** [comment]
I figured out how to solve this error:
In line 236 of preprocessing.py, 
change `image_name = train_instance['filename']`
to `        image_name = train_instance['filename']+'.jpg'`

**Comment by NPetsky** [comment]
I had to do the same to get it work only with .png
