### ISSUE TITLE
ValueError: total size of new array must be unchanged with custom data

### ISSUE THREAD

**Issue by thorstenwagner** [experiencor/basic-yolo-keras#95]
Hi,

thank you for that nice library. I was able to successfull apply the raccon detector. Now I want to apply it to my own data, but I always get the following exception:
```
python train.py -c config.json
Using TensorFlow backend.
Seen labels:	{'box': 2179}
Given labels:	[u'box']
Overlap labels:	set(['box'])
2017-12-19 13:50:41.315188: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2017-12-19 13:50:41.503167: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
pciBusID: 0000:01:00.0
totalMemory: 7.92GiB freeMemory: 7.80GiB
2017-12-19 13:50:41.503200: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
(128, 128)
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_1 (InputLayer)            (None, 4096, 4096, 3 0                                            
__________________________________________________________________________________________________
model_1 (Model)                 (None, 128, 128, 102 50547936    input_1[0][0]                    
__________________________________________________________________________________________________
conv_23 (Conv2D)                (None, 128, 128, 30) 30750       model_1[1][0]                    
__________________________________________________________________________________________________
reshape_1 (Reshape)             (None, 128, 128, 5,  0           conv_23[0][0]                    
__________________________________________________________________________________________________
input_2 (InputLayer)            (None, 1, 1, 1, 150, 0                                            
__________________________________________________________________________________________________
lambda_2 (Lambda)               (None, 128, 128, 5,  0           reshape_1[0][0]                  
                                                                 input_2[0][0]                    
==================================================================================================
Total params: 50,578,686
Trainable params: 50,558,014
Non-trainable params: 20,672
__________________________________________________________________________________________________
Traceback (most recent call last):
  File "train.py", line 140, in <module>
    _main_(args)
  File "train.py", line 136, in _main_
    debug              = config['train']['debug'])
  File "/datasets/toxin/basic-yolo-keras/frontend.py", line 385, in train
    self.model.compile(loss=self.custom_loss, optimizer=optimizer)
  File "/opt/conda/lib/python2.7/site-packages/keras/engine/training.py", line 860, in compile
    sample_weight, mask)
  File "/opt/conda/lib/python2.7/site-packages/keras/engine/training.py", line 459, in weighted
    score_array = fn(y_true, y_pred)
  File "/datasets/toxin/basic-yolo-keras/frontend.py", line 107, in custom_loss
    pred_box_wh = tf.exp(y_pred[..., 2:4]) * np.reshape(self.anchors, [1,1,1,self.nb_box,2])
  File "/opt/conda/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 224, in reshape
    return _wrapit(a, 'reshape', newshape, order=order)
  File "/opt/conda/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 48, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: total size of new array must be unchanged
```
This is my config.json:
https://gist.github.com/thorstenwagner/6e47d6c00ec25dd2af98ee570c4938cd

This is an example annotation file:
https://gist.github.com/thorstenwagner/33f891a50fa5dafcaad0ef130f9bf0ab

Any idea what the problem is? I guess there is something wrong with my ancor boxes. Maybe I get the format wrong. I thought it must be [box1_width,box1_height,box2_width , ...]. As I just need one box size I changed it to [260,260].

**Comment by thorstenwagner** [comment]
I found out that the anchors have to specified in as fraction of the grid size. But where do I find the grid size?

**Comment by thorstenwagner** [comment]
I've found the error! The nb_box fix set to 5. If I repeat the anchor box 0.825,0.825 5 times, it starts training (later it crashes because of memory issues, but this is another thing).
You should change the line https://github.com/experiencor/basic-yolo-keras/blob/master/frontend.py#L27

to

```
self.nb_box = len(anchors)/2
```
