### ISSUE TITLE
error: xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0

### ISSUE THREAD

**Issue by qmirsharif** [experiencor/basic-yolo-keras#96]
When I run python train.py -c config.json I get this error:
Using TensorFlow backend.
Traceback (most recent call last):
  File "train.py", line 140, in <module>
    _main_(args)
  File "train.py", line 76, in _main_
    config['model']['labels'])
  File "/home/ubuntu/boundingbox/basic-yolo-keras/preprocessing.py", line 18, in parse_annotation
    tree = ET.parse(ann_dir + ann)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0

**Comment by vperiyasamy** [comment]
Can I ask how you resolved this?

**Comment by geschaftsreise** [comment]
yeah same issue for me

**Comment by cemsaz** [comment]
If anyone is having this issue, I realized a simple **".DS_Store"** file was causing this error in my case (on Mac). I cleared them with this: **find . -name '.DS_Store' -type f -delete**, it works now.
