### ISSUE TITLE
Support single channel images

### ISSUE THREAD

**Issue by thorstenwagner** [experiencor/basic-yolo-keras#98]
Hi, it seems that your script always assume that the image has 3 channels:

input_image = Input(shape=(self.input_size, self.input_size, 3))

It would be nice if you change the script that it also supports single channgel images.

Thanks for the nice work!

**Comment by experiencor** [comment]
Hi @thorstenwagner! I received this request some time ago but have yet to find time to make the changes. Would be nice if you can help. I will label this issue as an enhancement.

**Comment by thorstenwagner** [comment]
I'm reading the depth from the annotations, and have adapted train.py / preprocessing.py and backend.py (only full_yolo). However I get the exception:
```
Traceback (most recent call last):
  File "train.py", line 144, in <module>
    _main_(args)
  File "train.py", line 113, in _main_
    anchors             = config['model']['anchors'])
  File "/datasets/toxin/basic-yolo-keras/frontend.py", line 49, in __init__
    self.feature_extractor = FullYoloFeature(self.input_size,self.input_depth)
  File "/datasets/toxin/basic-yolo-keras/backend.py", line 168, in __init__
    self.feature_extractor.load_weights(FULL_YOLO_BACKEND_PATH)
  File "/opt/conda/lib/python2.7/site-packages/keras/engine/topology.py", line 2622, in load_weights
    load_weights_from_hdf5_group(f, self.layers)
  File "/opt/conda/lib/python2.7/site-packages/keras/engine/topology.py", line 3143, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/opt/conda/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2247, in batch_set_value
    assign_op = x.assign(assign_placeholder)
  File "/opt/conda/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 573, in assign
    return state_ops.assign(self._variable, value, use_locking=use_locking)
  File "/opt/conda/lib/python2.7/site-packages/tensorflow/python/ops/state_ops.py", line 276, in assign
    validate_shape=validate_shape)
  File "/opt/conda/lib/python2.7/site-packages/tensorflow/python/ops/gen_state_ops.py", line 57, in assign
    use_locking=use_locking, name=name)
  File "/opt/conda/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/opt/conda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2958, in create_op
    set_shapes_for_outputs(ret)
  File "/opt/conda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2209, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/opt/conda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2159, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/opt/conda/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "/opt/conda/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimension 0 in both shapes must be equal, but are 3 and 32 for 'Assign' (op: 'Assign') with input shapes: [3,3,1,32], [32,3,3,3].
```

It seems that it has a problem with the pretrained weights (backend)... any idea why?

**Comment by experiencor** [comment]
@thorstenwagner The reason is that the size of the first convolutional layer is different. Previously the weight of this layer has size (3,3,3) but now it has size (3,3,3). So you will not be able to load the pre-trained weight of this layer. I suggest you to rename this layer then change line 167 of backend.py to ```self.feature_extractor.load_weights(FULL_YOLO_BACKEND_PATH, by_name=True)```.

By this way, the first layer is untrained but I think it will work just fine.

**Comment by thorstenwagner** [comment]
@experiencor 

OK, now the error is gone but iIget a new one. It seems to me that it reads the image it into the memory as RGB but I checked it twice (it is just 8 bit).
Any hint for me?
```
  File "train.py", line 144, in <module>
    _main_(args)
  File "train.py", line 140, in _main_
    debug              = config['train']['debug'])
  File "/datasets/toxin/basic-yolo-keras/frontend.py", line 447, in train
    max_queue_size   = 8)
  File "/opt/conda/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/keras/engine/training.py", line 2147, in fit_generator
    class_weight=class_weight)
  File "/opt/conda/lib/python2.7/site-packages/keras/engine/training.py", line 1833, in train_on_batch
    check_batch_axis=True)
  File "/opt/conda/lib/python2.7/site-packages/keras/engine/training.py", line 1414, in _standardize_user_data
    exception_prefix='input')
  File "/opt/conda/lib/python2.7/site-packages/keras/engine/training.py", line 153, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking input: expected input_1 to have shape (None, 512, 512, 1) but got array with shape (8, 512, 512, 3)
```

**Comment by experiencor** [comment]
The reason is that you are still feeding (512,512,3) to the network which now accepts (512,512,1). You need to change ```x_batch``` on line 151 of ```preprocessing.py``` to:

```x_batch = np.zeros((r_bound - l_bound, self.config['IMAGE_H'], self.config['IMAGE_W'], 3))```

You may also need to revise the augmentation code.

**Comment by thorstenwagner** [comment]
@experiencor 
I've adapted several lines and I'm now able to train on single channel images. The number of channels is evaluated using the first training image.
However,I'm still not able to predict a single channel image. This is the error:

```
Traceback (most recent call last):
  File "predict.py", line 111, in <module>
    _main_(args)
  File "predict.py", line 102, in _main_
    boxes = yolo.predict(image)
  File "/datasets/toxin/basic-yolo-keras/frontend.py", line 255, in predict
    netout = self.model.predict([input_image, dummy_array])[0]
  File "/opt/conda/lib/python2.7/site-packages/keras/engine/training.py", line 1772, in predict
    check_batch_axis=False)
  File "/opt/conda/lib/python2.7/site-packages/keras/engine/training.py", line 141, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking : expected input_1 to have 4 dimensions, but got array with shape (1, 512, 512)
```

This is the adapted predict funcktion in frontend.py:
```
def predict(self, image):
        image = cv2.resize(image, (self.input_size, self.input_size))
        image = self.feature_extractor.normalize(image)
        if len(image.shape)==3:
                input_image = image[:,:,::-1]
        else:
                input_image = image
        input_image = np.expand_dims(input_image, 0)
        dummy_array = dummy_array = np.zeros((1,1,1,1,self.max_box_per_image,4))

        netout = self.model.predict([input_image, dummy_array])[0]
        boxes  = self.decode_netout(netout)
```

I'm not how to fix. It seems that the dummy_array has the wrong format. I would be happy of you comment on it.

**Comment by ttorkar** [comment]
I'm not as familar with the python version but it looks like it wants the 4 in the dummy array to be 1.

**Comment by thorstenwagner** [comment]
But as far as I understand the 4 saves the x,y,width and height variables for each box. These variables should be independent of the number of image channels.

**Comment by ttorkar** [comment]
Can you print out the shape of both the image and dummy array before it runs the prediction. I'm not at my computer so I'm only partially able to help.

**Comment by thorstenwagner** [comment]
input_image:
```
(1, 512, 512)
```
dummy_array:
```
 (1, 1, 1, 1, 150, 4)
```

**Comment by ttorkar** [comment]
I'm not sure where input_1 is being defined but have you changed the dimensionality in backend.py? The issue is with the input image, not the dummy array.

**Comment by thorstenwagner** [comment]
Yes! The full yolo model now accepts 1 dimensional images:
https://github.com/thorstenwagner/basic-yolo-keras/blob/master/backend.py#L38

**Comment by ttorkar** [comment]
Is it working? If not, try harcoding in the input depth in backend.py

**Comment by thorstenwagner** [comment]
It is working during training! But for prediction I get error above.

**Comment by thorstenwagner** [comment]
@experiencor  Any helpfull suggestions?

**Comment by thorstenwagner** [comment]
Solved! Keras expects for images a channel axis. In case of greyscale images this has just the dimension 1, but it still need it.
```
 def predict(self, image):
        image = cv2.resize(image, (self.input_size, self.input_size))
        image = self.feature_extractor.normalize(image)
        if len(image.shape)==3:
                input_image = image[:,:,::-1]
        else:
                input_image = image
                input_image = image.reshape((image.shape[0],image.shape[1],1))
        input_image = np.expand_dims(input_image, 0)
        dummy_array = dummy_array = np.zeros((1,1,1,1,self.max_box_per_image,4))
        netout = self.model.predict([input_image, dummy_array])[0]
        boxes  = self.decode_netout(netout)
```

**Comment by thorstenwagner** [comment]
Basically, it is now working for single channel images. But only for FullYolo model.
